# Generated by Django 3.2.8 on 2024-02-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('supports_attachments', models.BooleanField(default=False, verbose_name='supports attachments')),
                ('code_name', models.CharField(blank=True, max_length=128, unique=True)),
                ('manual_only', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Messenger',
                'db_table': 'control_server_messengers',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('with_honeypage', models.BooleanField(default=False)),
                ('with_suspicious_honeypage', models.BooleanField(default=False)),
                ('with_meta_tags_honeypage', models.BooleanField(default=False)),
                ('with_honeymail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('manual', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to=settings.AUTH_USER_MODEL)),
                ('honeymail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='honeypot.honeymail')),
                ('honeypage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiment', to='honeypot.honeypage')),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='control_server.messenger')),
            ],
            options={
                'verbose_name': 'Experiments',
                'db_table': 'control_server_experiments',
                'ordering': ['-pk'],
            },
        ),
    ]
