# Generated by Django 3.2.8 on 2024-02-26 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserFingerprintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_url', models.CharField(max_length=1024)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('feature_fp_version', models.CharField(blank=True, default='undefined', max_length=45)),
                ('features', models.CharField(max_length=1024)),
                ('feature_ua', models.CharField(max_length=1024)),
                ('browser_like_data', models.CharField(max_length=1024)),
                ('client_ua', models.CharField(max_length=512)),
                ('parsed_ua', models.CharField(max_length=1024)),
                ('plugins', models.CharField(max_length=1024)),
                ('client_data', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Browser Fingerprint Log',
                'db_table': 'honeypot_browser_fingerprint_logs',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=1024, unique=True)),
                ('fp_js_version', models.CharField(blank=True, default='3.0.1', max_length=45)),
                ('users', models.ManyToManyField(blank=True, related_name='fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fingerprint',
                'db_table': 'honeypot_fingerprints',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_url', models.CharField(blank=True, max_length=1024)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('fingerprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='fingerprint_logs', to='honeypot.fingerprint')),
                ('components', models.CharField(blank=True, max_length=60000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fingerprint Log',
                'db_table': 'honeypot_fingerprint_logs',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='HoneydataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honeydata_type', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'HoneydataType',
                'db_table': 'honeypot_honeydatatypes',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='Honeymail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Honeymail',
                'db_table': 'honeypot_honeymails',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='Honeypage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(default='', max_length=128)),
                ('path', models.CharField(blank=True, default='', max_length=128)),
                ('protocol', models.CharField(default='http', max_length=5)),
                ('pdf_payload', models.CharField(blank=True, default='', max_length=256)),
                ('suspicious', models.BooleanField(blank=True, default=False)),
                ('with_meta_tags', models.BooleanField(blank=True, default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='children', to='honeypot.honeypage')),
            ],
            options={
                'verbose_name': 'Honeypage',
                'db_table': 'honeypot_honeypages',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.TextField(blank=True)),
                ('http_host', models.CharField(blank=True, max_length=512)),
                ('subdomain', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_params', models.TextField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=24, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('get', models.TextField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('cookies', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('files', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=4096)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('location', models.TextField(blank=True, verbose_name='GeoIP 2 Location')),
                ('request', models.TextField(blank=True, verbose_name='Request')),
                ('response', models.TextField(blank=True, verbose_name='Response')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Log',
                'db_table': 'honeypot_access_logs',
                'ordering': ['-pk'],
                'default_permissions': ['view'],
            },
        ),
    ]
