import os
import time

root = os.path.join("..", "config", "scripts")
output = os.path.join("..", "output", "fingerprinting.js")

script_text = "/* Script generated by combine_scripts.py {} */\n".format(
    time.strftime('%X %x %Z')
)

scripts_to_combine = [
    "feature_fp.js",
    "fp.min",
    "fingerprintjs.js"
]

paths = [os.path.join(root, script_name) for script_name in scripts_to_combine]

for path in paths:
    with open(path, "r") as file:
        content = file.read()
        script_text += "\n"
        script_text += content

with open(output, "w") as file:
    file.write(script_text)
    print("Combined fingerprinting script written to " + os.path.abspath(output))
